//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cutomer_id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Mobile_No { get; set; }
        public string Customer_Address { get; set; }
    }
}
