//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public int Product_Quantity { get; set; }
        public int Product_Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
